### ISSUE TITLE
Uniswap Protocol Deployment - Command 'pip3' not found

### ISSUE THREAD

**Issue by chrishobcroft** [empowerthedao/uniswap-aragon-app#1]
Steps to recreate:

- Following the instructions here: https://github.com/empowerthedao/uniswap-aragon-app/tree/master/uniswap-protocol

- Run `pip3 install virtualenv`

- See error:

```
chrishobcroft@thinkpad:~/uniswap-aragon-app$ pip3 install virtualenv

Command 'pip3' not found, but can be installed with:

sudo apt install python3-pip
```

Suggest having a section clearly listing the assumed pre-requisites (including version numbers), and links to where they each can be installed / download.

e.g. npm, truffle, ganache-cli, yarn, python3-pip, ?, other contracts which are assumed (ENS?).

**Comment by willjgriff** [comment]
And after doing what it says does it work?

**Comment by chrishobcroft** [comment]
No...

```
Command 'virtualenv' not found
```

and then

```
bash: env/bin/activate: No such file or directory
```
